uwolfer/gerrit-rest-java-client

- src/main/java/com/google/gerrit/extensions/api/projects/BranchInfo.java
- src/main/java/com/google/gerrit/extensions/api/projects/ChildProjectApi.java
- src/main/java/com/google/gerrit/extensions/api/projects/ProjectApi.java
- src/main/java/com/google/gerrit/extensions/api/projects/Projects.java
- src/main/java/com/google/gerrit/extensions/api/projects/PutDescriptionInput.java
- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/BranchInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/GerritRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/BranchInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/BranchInfoParserBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/BranchInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/branches.json
Hi Urs,
I've reimplemented this by pulling in some more google classes and added a test.
Let me know if you have any problems with this.
Thanks,
Tim
> feat: implement branches().get() method to ProjectApi

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/TagApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/TagInfoParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/TagInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/BranchApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/TagApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/TagInfoParserBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/TagInfoParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/tag.json
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/tags.json
Hi!
Thanks for the great library, I use it in my project at work.
But I missed TagApi so I've implemented it in this commit.
Please let me know if there is anything that could be improved in it.
Best Regards,
Pavel.
> TagApi implemented

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/FileApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/FileApiRestClientTest.java
Signed-off-by: Edwin Kempin <ekempin@google.com>
> implement file method #diffRequest

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Signed-off-by: Edwin Kempin <ekempin@google.com>
> implement change method #restore

- README.md
- appveyor.yml
- src/test/java/com/urswolfer/gerrit/client/rest/RealServerTest.java
For an example how the test results are displayed online see [here](https://ci.appveyor.com/project/sschuberth/gerrit-rest-java-client/build/1.0.8/tests).
> Use AppVeyor for Windows CI builds

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Implementing comments for the Gerrit Change API.  I tried to adhere to the way the other unit tests were written.  Let me know if I should change anything.
> Implementing Comments for the Gerrit Change API

- examples/Basic.groovy
Please have a look at the individual commit messages for the details.
> Improve the Groovy code example

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
This adds support to get a list of ChangeInfo that will be
submitted together.
> Add support for "Changes Submitted Together"

- src/main/java/com/google/gerrit/extensions/api/changes/ChangeApi.java
- src/main/java/com/google/gerrit/extensions/api/changes/ChangeEditApi.java
- src/main/java/com/urswolfer/gerrit/client/rest/RestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeEditApiRestClient.java
Implement ChangeEditApiRestClient.java to create ChangeEdit, add/modify file, publish edit.
Also modified other files to set Code Review (Review +2, verfy +1) and submit a change.
The following files are updated as well:
ChangeApi.java
ChangeApiRestClient.java
ChangeEditApi.java
GerritRestClient.java
RestClient.java
> implement ChangeEditApiRestClient

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/MessagesParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/MessagesParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/ChangeMessageInfoBuilder.java
Hi! As a follow-up on the discussion in PR #100, I added the missing copyright header to the files created in PR #96.
> Added missing copyright

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/RestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/SshKeysParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/SshKeyParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/accounts/self/sshkey.json
- src/test/resources/com/urswolfer/gerrit/client/rest/http/accounts/self/sshkeys.json
Adding SSH Key addition, list and deletion to AccountsApi
> Extending AccountsApi with SSH key functionality

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Hi, I have implemented the _getPastAssignees()_ function in _ChangeApiRestClient_. 
Please let me know if some fixings are needed. Thank you! 🙂
> implemented getPastAssignees

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Hi, I implemented the small functionality _drafts_ in ChageApiRestClient. 
Please, let met me know if there's anything that needs to be changed.
> Implemented drafts in ChangeApiRestClient

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
Hi!
This is just a small commit to add the method _description_ in RevisionApiRestClient. I hope everything is ok!
> Added revision description method

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/MergeableInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/MergeableInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/MergeableInfoBuilder.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/mergeable.json
Hi, I have implemented the function _mergeable_ in RevisionApiRestClient. 
Can you please check if everything is ok? 
Also, while working on this I noticed an extra blank line in _HashtagsParser_ and I removed it. Since it was just a small fix I added it in this PR, despite being just a cosmetic change.
> implemented get mergeable in RevisionApiRestClient

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
Hi, I have added the function _robotComments()_ in RevisionRestApiClient. 
Please, let me know if everything is ok or if some changes are needed. Thank you!
> Added robotComments() in RevisionRestApiClient

- src/main/java/com/urswolfer/gerrit/client/rest/Version.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/SshKeysParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/CommitInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/EditInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/HashtagsParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/IncludedInInfoParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/RealServerTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/GitHubOAuthLoginSimulationServlet.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/LoginSimulationServlet.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/UserAgentHttpRequestInterceptorTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/SshKeyParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/CommitInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/FileApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/IncludedInInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/MergeableInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/ChangeMessageInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/MergeableInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/RobotCommentInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/BranchApiRestClientTest.java
Hi, I did a pass on the whole code and made some refactoring. 
To summarise I did the following modifications: 
- removed unused import statements
- removed extra blank lines
- enforced the same coding style choices through the whole project (e.g., use of @author tag)
- replaced anonymous functions with lambda expressions
- added missing copyright headers
Let me know if you preferred some things as they were before. Thank you!
> General refactoring

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ActionInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ActionInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/ActionInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/actions.json
Hi! 
I have added the _actions()_ method in RevisionApiRestClient. 
This is something unrelated to the issue I posted two days ago, but I was already working on it so I am committing it before starting to work on the content of the issue. 
Let me know if something needs to be fixed. Thank you!
> Implemented method actions in RevisionApiRestClient

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewInfoParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewInfoParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/files-reviewed.json
this method is required for https://github.com/uwolfer/gerrit-intellij-plugin/pull/396 to work.
> Implement RevisionApi.reviewed()

- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClientTest.java
> replace query2 to query

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Hi, I have added the methods _setMessage_ and _setHashtags_ in ChangeApiRestClient.
As usual, let me know if everything is fine or if something needs to be changed.
> implemented methods setMessage and setHashtags

- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
This patch fixes retrieving of files with "+" in the name
> Disable implicit URL normalization

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
This commit remove unused branches set  in projects and add single branch string. It call with parameter api/project/?b=<branch>
> Add search branch capability with /projects/

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/CommitApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/parsers/ProjectCommitInfoParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/BranchApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/CommitApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/LabelApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectCommitInfoParserBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/TagApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/parsers/ProjectCommitInfoParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/parsers/commit.json
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/parsers/includedIn.json
Implementing the projects/projectName/commits endpoint
and it's get and includedIn methods
Added tests for these parsers and api clients
> Implement projects/projectName/commits endpoint

- src/main/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsParserBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/accounts/AccountsRestClientTest.java
Adding implementation and tests for the account
creation endpoint.
> Implement accounts/create endpoint

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/TagApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/TagApiRestClientTest.java
Implementing methods for tag creation
and deletion.
Added tests for tagApiclient methods
> Implementing tag creation/deletion

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ChildProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ChildProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/projectAccessInfo.json
Added further methods for projectsAPI
- Created ChildProjectApiRestClient.
- Added more methods to ProjectApiRestClient
- Updated tests for ProjectParser and new clients endpoints
> Implementing further Project endpoints
