- src/main/java/com/google/gerrit/extensions/restapi/BinaryResult.java
- src/main/java/com/google/gerrit/extensions/restapi/Url.java
Current gerrit 0.9.7.5 doesn't support java 1.6, it show as "cannot login", and throws an exception.
And, under Mac OS X, java 1.6 by Apple looks better than 1.7+ by Oracle.
> support java 1.6

- src/test/resources/.gitattributes
Gson is strict about the Unix line ending when checking for the
non-execute prefix [1], so ensure to have Unix line endings even on e.g.
Windows.
Fixes #35.
[1] https://google.github.io/gson/apidocs/com/google/gson/stream/JsonReader.html#nonexecuteprefix
> Force JSON test resources to have Unix-style LF line endings

- src/test/java/com/urswolfer/gerrit/client/rest/http/GerritRestClientTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/config/server/.gitattributes
With these commits, all tests pass on Windows.
@uwolfer Have you considered using AppVeyor in addition to Travis CI in order to run tests on Windows and prevent future regressions?
> Fix tests on Windows

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClientTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/groups/group.json
- src/test/resources/com/urswolfer/gerrit/client/rest/http/groups/groups.json
I have a need to perform operations on Gerrit groups, but there is currently no support in the API.  I've implemented support for many of the operations defined in the GroupAPI.  One thing I wasn't able to get working is support for parsing the "visibile_to_all" option.  You'll see this as a failing unit test, so hopefully someone knows how to correctly parse the project options.  (see ./src/test/resources/com/urswolfer/gerrit/client/rest/http/groups/groups.json for an example of the "visible_to_all" option)
> Adding support for Gerrit group operations

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParser.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/AbstractParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
I added some tests for it, too. There is an untested branch for the String-based project creation. Let me know if you would like me to cover that part, too.
I'm implementing project create because I'm depending on this client for a project. I have used the snapshot locally, and I am able to create a named project with it.
> Implemented project create for the gerrit projects API.

- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
Any Group IDs which contain spaces (or other characters which require URL encoding) are currently failing when the Gerrit REST API calls are made.  To resolve this, the ID needs to be URL encoded prior to submitting the request.
> URLEncode the Group ID to handle cases where the ID contains spaces

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
Sorry for not including this in my last pull request.  I stumbled across it just after the previous pull request was merged.
> URLEncode the project name when constructing the URL

- appveyor.yml
This party reverts commit a25f9b0 and bumps the Maven version to 3.3.9.1
as 3.3.9 indeed is not available on Chocolatey.
> Revert to using Chocolatey to install Maven

- pom.xml
- src/main/java/com/google/gerrit/extensions/api/changes/Changes.java
- src/main/java/com/google/gwtorm/server/StandardKeyEncoder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
This allows for a more convenient use of the API in the same way the Gerrit web UI is used when entering a search term.
> Conveniently encode the query string like the Gerrit web UI does

- src/main/java/com/urswolfer/gerrit/client/rest/GerritAuthData.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
This change introduces a new contructor in the GerritAuthData class.
The new constructor takes an additional "httpPassword" argument,
which is used to identify whether the password being sepcified is
a special Gerrit HTTP password token (typically a password which
can be generated for each user on their Settings -> HTTP Password
page).  When set to false (the default), the password is assumed
to be a valid password for whatever authentication source Gerrit
is configured to use for normal user authentication.  When set to
true, the password is assumed to be a HTTP Password maintained
internally by Gerrit.
This fix is intended to resolve a problem where specifying an
HTTP Password for REST API calls will attempt to authenticate
against the /login page.  When Gerrit is configured to …
> Avoid /login authentication when using Gerrit HTTP password tokens.

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
This adds support for the "Submit Preview" feature which can
be used to download a file containing thin bundles of all modified
projects if this change was submitted.
> Add support for "Submit Preview"

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/MessagesParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/MessagesParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/ChangeMessageInfoBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/messages.json
Since it seemed to me that it was still not there, I have implemented the messages() function, together with the related tests.
Since modifying the constructor of ChangeApiRestClient to accept an object of the new class MessagesParser would have requested further modifications in the code-base, I took the liberty to add a setter for messagesParser. 
I hope this is not a problem. If the PR is fine, I will fix this in a follow-up PR.
Thank you!
Best, 
Enrico
> Implemented messages function for ChangeApiRestClient

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ListChangesOptionByVersion.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/config/ServerRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/RealServerTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Do not use all the possible ListChangeOption values when requesting a change
details. Use the version string returned by the Gerrit backend in order to select
only the options actually supported by the backend.
Relates to #97
> Restrict ListChangeOption by Gerrit version

- src/main/java/com/google/gerrit/extensions/common/RobotCommentInfo.java
- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RobotCommentsParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RobotCommentsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/GerritAssert.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/common/RobotCommentInfoBuilder.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/robotcomments.json
Hi!
I have implemented the possibility to retrieve robot comments from Gerrit. If I am not mistaken, it still needed to be added to the project.
I implemented also the related tests and they all passed. 
However, there is something I would like to discuss with you. In the json file created for the tests ("robotcomments.json"), I had to change the fields robotId and robotRunId to robot_id and robot_run_id, respectively. If left in their original formulation, Gson does not recognize them. 
This does not match the documentation of the Gerrit REST api, where they are reported as robotId and robotRunId.
Investigating the reason behind this, I found that the cause is likely to be the field naming policy implemented in GsonFactory. 
It is probably possible to act on this, but it might require a …
> Implemented robotComment functionalities

- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsRestClientTest.java
This change makes sure to honor `projects().list().withTree(true)` when building the query.
> Honor projects.list().withTree parameter

- src/main/java/com/urswolfer/gerrit/client/rest/GerritApiImpl.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangesRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/DraftsApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/HashtagsParserTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ReviewerApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
Hi! I added the _getAssignee( )_ function in the _ChangeApiRestClient_ class. 
While I was working on it, I did some small refactoring as well. I did not open a separate PR for those since they are quite small changes. They are the following:
- Added blank space between comma and parameter in _DraftApiRestClientTest_.
- Removed unused import in _HashtagParserTest_.
- Moved the method _getHashtags()_ in _ChangeApiRestClient_ to follow the order of the implemented interface _ChangeApi_.
> Added getAssignee

- src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/LoginCache.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/GerritRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/GitHubOAuthLoginSimulationServlet.java
When Gerrit is configured with a GitHub/OAuth auth type,
the form authentication is technically available but not
in a way that can be automatically used by the REST Client.
GitHub may require additional authentication verification
methods such as 2FA that are incompatible with a batch use
by the Gerrit REST client library.
Detect the OAuth handshake by looking at the redirection
path containing the github plugin scope selection and
avoid attempting the form authentication mechanism again.
Closes #107
> Avoid spamming Gerrit when using GitHub/OAuth authentication

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Hi!
I have added the implementation of the method _revertSubmission_. Let me know if everything is ok or something needs to be changed. 
In the tests, I followed a similar implementation to the one used for the _testRevertChange_ methods. 
My understanding is that, in these methods, the fact that the entity returned is indeed correct is not checked. They only check that the post request is performed correctly.
Should we add this kind of check or the current implementation is fine?
> implemented revertSubmission

- src/main/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/groups/GroupsParserTest.java
When returning Lists of GroupInfo the name field
was left null update is to parse this out of the
returned map so that group names can be queried.
> Correct GroupsPaser.java leaving names empty

- .gitignore
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java
Changing signature to return ChangeInfo as defined by Gerrit API:
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#rebase-change
Added test case for the new implementation.
Extending gitignore to ignore files produced by TestNG
> Implement rebase change

- src/main/java/com/urswolfer/gerrit/client/rest/gson/GsonFactory.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParserBuilder.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/projects/ProjectsParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/projects/configInfo.json
Adding implementation of project/config.
Get and Put commands implemented.
Added new parser method to ProjectsParser.
Added new tests to ProjectParserTest and
ProjectApiClientTest
> Implement Project config endpoints

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeEditApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/parsers/CommitInfosParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeEditApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/parsers/CommitInfosParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/parsers/changeEditInfo.json
Implementing methods on the
change/edit endpoints.
Updates to ChangeEditApiRestClient
- Constructor now uses commitInfoParser to parse EditInfo objects
- New test class ChangeEditApiRestClientTest added
- private classes for edit inputs that Gerrit does not provide in api libs.
> Implementing change edit endpoints

- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/CommentApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RobotCommentApiRestClient.java
- src/main/java/com/urswolfer/gerrit/client/rest/http/changes/parsers/CommentsParser.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/CommentApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/RobotCommentApiRestClientTest.java
- src/test/java/com/urswolfer/gerrit/client/rest/http/changes/parsers/CommentsParserTest.java
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/parsers/comment.json
- src/test/resources/com/urswolfer/gerrit/client/rest/http/changes/parsers/robotcomment.json
Adding rest Clients to implement comment and
robotcomment endpoint to return single comment
when queried and allow their deletion.
Tests added for single parser methods and
getting client from RevisionApiRestClient.
> Implementing Comment and RobotComment api
